### ISSUE TITLE
Typo, missing declaration and some minor problems

### ISSUE THREAD

**Issue by KONY128** [linxuyalun/linxuyalun.github.io#5]
https://linxuyalun.github.io/2021/02/18/golang-struct-with-embeded-interface/

**Main Problems:**

Typo: 

- Actiuon -> Action

Missing declaration: 

- In the first block of *Details of Interface*, the declaration of Interface `Action` is missing

**Minor Problems:**

- Blocked fields are not unified at this blog. Some are `Types`, some are `Values`, some are `Printed lines` and some are `Method Names`. And they're missing somewhere
- One intermediate implicit logic being ignored: `Person` implement interface `Action` so go compiler makes `* Person` implement interface `Action`. This is the actual reason for the context. (Missing `* Person` implement interface `Action`)

**Comment by linxuyalun** [comment]
Thanks for the issue!

The unified blocked fields problem... Yeah, you are right, but I will not fix them, because of the time cost.

Except for that, all of the above stuff is nice and meaningful, I will fix it. Thanks a lot 🌹
